language: php

php:
  - 5.6

env:
  CODECLIMATE_REPO_TOKEN: 153dcdbbca5ef9c1c42d3ce2a46df3e441951a99d9de6049f49d983c9464fa2d

addons:
  code_climate:
    repo_token: 153dcdbbca5ef9c1c42d3ce2a46df3e441951a99d9de6049f49d983c9464fa2d

install:
  - composer install

after_script:
  - vendor/bin/test-reporter
